"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";
import { useRouter } from "next/navigation";
import type { Client } from "@/lib/types";

export default function NewContract(){const router=useRouter();const [clients,setClients]=useState<Client[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);useEffect(()=>{fetch('/api/clients').then(r=>r.json()).then(setClients)},[]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');try{const f=new FormData(e.currentTarget);const file=f.get('file') as File;if(!file?.name.toLowerCase().endsWith('.docx'))throw new Error('Seleccione un archivo .docx');const u=await fetch('/api/uploads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,size:file.size})});const upload=await u.json();if(!u.ok)throw new Error(upload.error);const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {error:uploadError}=await supabase.storage.from('contracts').uploadToSignedUrl(upload.path,upload.token,file,{contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});if(uploadError)throw uploadError;const r=await fetch('/api/contracts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:f.get('title'),clientId:f.get('clientId'),uploadPath:upload.path})});const body=await r.json();if(!r.ok)throw new Error(body.error);router.push(`/admin/contratos/${body.id}`)}catch(err){setError(err instanceof Error?err.message:'No fue posible crear el contrato');setLoading(false)}}
return <><div className="mb-7"><h1 className="text-3xl font-extrabold">Nuevo contrato</h1><p className="muted mt-1">Cargue el Word, compruebe la conversión y envíelo.</p></div><form onSubmit={submit} className="card p-6 max-w-2xl space-y-5"><label><span className="label">Título del contrato</span><input name="title" className="input" required minLength={3} placeholder="Contrato de prestación de servicios"/></label><label><span className="label">Cliente y firmante</span><select name="clientId" className="input" required defaultValue=""><option value="" disabled>Seleccione un cliente</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name} · {c.email}</option>)}</select></label><label><span className="label">Documento Word</span><input name="file" className="input" type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required/><span className="muted text-xs mt-2 block">DOCX sin macros, máximo 20 MB. La conversión puede tardar unos segundos.</span></label>{error&&<p className="p-3 bg-red-50 text-red-700 text-sm rounded-lg">{error}</p>}<button className="btn btn-primary w-full" disabled={loading}>{loading&&<span className="spinner"/>}{loading?'Validando y convirtiendo…':'Crear y convertir contrato'}</button></form></>}
