"use client";
import { FormEvent, useEffect, useState } from "react";
import type { Client } from "@/lib/types";
import { Plus, X } from "lucide-react";

export default function ClientsPage(){const [clients,setClients]=useState<Client[]>([]);const [open,setOpen]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(true);async function load(){setLoading(true);const r=await fetch('/api/clients');if(r.ok)setClients(await r.json());setLoading(false)}useEffect(()=>{let active=true;fetch('/api/clients').then(async r=>{if(active&&r.ok)setClients(await r.json())}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const r=await fetch('/api/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});const b=await r.json();if(!r.ok){setError(b.error);return}setOpen(false);e.currentTarget.reset();await load()}
return <><div className="flex justify-between items-start gap-4 mb-7"><div><h1 className="text-3xl font-extrabold">Clientes</h1><p className="muted mt-1">Destinatarios de sus contratos.</p></div><button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={18}/>Nuevo cliente</button></div>
<section className="card overflow-hidden">{loading?<p className="p-8 muted">Cargando…</p>:clients.length===0?<p className="p-8 muted text-center">Cree su primer cliente.</p>:<div className="divide-y divide-slate-100">{clients.map(c=><div className="p-4 grid md:grid-cols-[1.3fr_1fr_1fr] gap-2" key={c.id}><div><p className="font-bold">{c.name}</p><p className="muted text-sm">{c.company||'Sin empresa'}</p></div><p className="text-sm">{c.email}</p><p className="text-sm muted">{c.phone||'—'}</p></div>)}</div>}</section>
{open&&<div className="fixed inset-0 bg-slate-950/35 grid place-items-center p-4 z-50"><form className="card p-6 w-full max-w-lg space-y-4" onSubmit={submit}><div className="flex justify-between"><h2 className="text-xl font-extrabold">Nuevo cliente</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><Field name="name" label="Nombre completo" required/><Field name="email" label="Correo" type="email" required/><Field name="company" label="Empresa"/><Field name="phone" label="Teléfono"/><label><span className="label">Notas</span><textarea className="input" name="notes" rows={3}/></label>{error&&<p className="text-red-700 text-sm">{error}</p>}<button className="btn btn-primary w-full">Guardar cliente</button></form></div>}</>}
function Field({name,label,type='text',required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label><span className="label">{label}</span><input className="input" name={name} type={type} required={required}/></label>}
