"use client";
import { use, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2, Download, FileSignature, LockKeyhole } from "lucide-react";
import { PdfViewer } from "@/components/pdf-viewer";
import { SignaturePad } from "@/components/signature-pad";

type Info={title:string;signerName:string;signerEmail:string;signerEmailMasked:string;documentHash:string;status:string;signedAt:string|null;otpBlocked:boolean;expiresAt:string;currentDate:string;publicId:string};
export default function SignPage({params}:{params:Promise<{token:string}>}){const {token}=use(params);const [info,setInfo]=useState<Info|null>(null);const [error,setError]=useState('');const [read,setRead]=useState(false);const [signature,setSignature]=useState('');const [otpSent,setOtpSent]=useState(false);const [code,setCode]=useState('');const [proof,setProof]=useState('');const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [done,setDone]=useState<{publicId:string;finalHash:string}|null>(null);
useEffect(()=>{fetch(`/api/sign/${token}`).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setInfo(b);setTimeout(()=>fetch(`/api/sign/${token}/view`,{method:'POST'}),900)}).catch(e=>setError(e.message))},[token]);
const reachedEnd=useCallback(()=>{if(read)return;setRead(true);fetch(`/api/sign/${token}/read`,{method:'POST'})},[read,token]);
async function otp(action:'request'|'verify'){setBusy(true);setError('');const r=await fetch(`/api/sign/${token}/otp`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='request'?{action}:{action,code})});const b=await r.json();setBusy(false);if(!r.ok){setError(b.error);return}if(action==='request')setOtpSent(true);else setProof(b.proof)}
async function sign(){setBusy(true);setError('');const r=await fetch(`/api/sign/${token}/submit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({proof,signature,consent})});const b=await r.json();setBusy(false);if(!r.ok){setError(b.error);return}setDone(b)}
if(error&&!info)return <Centered><h1 className="text-2xl font-extrabold">Enlace no disponible</h1><p className="muted mt-2">{error}</p></Centered>;if(!info)return <Centered><p>Cargando contrato…</p></Centered>;if(done)return <Centered><CheckCircle2 className="text-emerald-600 mx-auto" size={60}/><h1 className="text-2xl font-extrabold mt-4">Firma completada</h1><p className="muted mt-2">El documento fue sellado y el administrador recibió la confirmación.</p><Link className="btn btn-primary mt-6" href={`/verify/${done.publicId}`}>Verificar certificado</Link><code className="block text-xs break-all muted mt-5">SHA-256: {done.finalHash}</code></Centered>;if(info.status==='SIGNED')return <Centered><CheckCircle2 className="text-emerald-600 mx-auto" size={54}/><h1 className="text-2xl font-extrabold mt-3">Este contrato ya fue firmado</h1><div className="flex gap-2 justify-center mt-5"><a className="btn btn-primary" href={`/api/sign/${token}/pdf`} target="_blank"><Download size={17}/>Descargar firmado</a><Link className="btn btn-secondary" href={`/verify/${info.publicId}`}>Verificar</Link></div></Centered>;
return <main><header className="bg-white border-b border-slate-200 sticky top-0 z-30"><div className="max-w-6xl mx-auto p-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 font-extrabold"><FileSignature className="text-teal-700"/>Mekanálisis</div><a className="btn btn-secondary text-sm" href={`/api/sign/${token}/pdf`} target="_blank"><Download size={16}/>Descargar PDF</a></div></header><section className="max-w-6xl mx-auto p-4"><div className="card p-5 my-4"><h1 className="text-2xl font-extrabold">{info.title}</h1><p className="mt-2">Firmante: <strong>{info.signerName}</strong> · {info.signerEmail}</p><p className="text-xs muted break-all mt-3">Hash SHA-256: {info.documentHash}</p></div><div className="text-center py-3"><p className="font-bold">Lea el documento completo</p><p className="muted text-sm">Deslice hasta el final para habilitar la firma.</p></div><div className="max-w-[790px] mx-auto"><PdfViewer url={`/api/sign/${token}/pdf`} onEnd={reachedEnd}/></div>
<section className={`card max-w-2xl mx-auto p-6 my-8 ${!read?'opacity-50 pointer-events-none':''}`}><div className="flex items-center gap-3 mb-5"><span className="h-10 w-10 grid place-items-center rounded-full bg-teal-50 text-teal-700"><FileSignature/></span><div><h2 className="text-xl font-extrabold">Firmar aquí</h2><p className="muted text-sm">{info.currentDate}</p></div></div>{!read&&<p className="p-3 rounded-lg bg-amber-50 text-amber-800 mb-4">La firma se habilita al llegar al final del documento.</p>}<p className="label">Dibuje su firma</p><SignaturePad onChange={setSignature}/>
<div className="mt-6 border-t border-slate-200 pt-5"><h3 className="font-extrabold flex items-center gap-2"><LockKeyhole size={18}/>Verificación de identidad</h3><p className="muted text-sm mt-1">Enviaremos un código de 6 dígitos a {info.signerEmailMasked}.</p>{!otpSent?<button className="btn btn-primary mt-4" disabled={!signature||busy||info.otpBlocked} onClick={()=>otp('request')}>Enviar código</button>:!proof?<div className="flex gap-2 mt-4"><input className="input max-w-[180px] text-center text-xl tracking-[.35em]" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" placeholder="000000"/><button className="btn btn-primary" disabled={code.length!==6||busy} onClick={()=>otp('verify')}>Verificar</button></div>:<p className="mt-4 text-emerald-700 font-bold flex gap-2 items-center"><CheckCircle2 size={18}/>Correo verificado</p>}</div>
{proof&&<><label className="flex gap-3 mt-6 items-start"><input type="checkbox" className="mt-1" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span className="text-sm">Declaro que leí el documento completo, que la firma dibujada me representa y que acepto firmarlo electrónicamente.</span></label><button className="btn btn-primary w-full mt-5" disabled={!consent||busy} onClick={sign}>{busy?'Generando documento firmado…':'Completar firma electrónica'}</button></>}{error&&<p className="mt-4 p-3 rounded bg-red-50 text-red-700 text-sm">{error}</p>}</section></section></main>}
function Centered({children}:{children:React.ReactNode}){return <main className="min-h-screen grid place-items-center p-5"><section className="card p-8 max-w-lg text-center">{children}</section></main>}
