"use client";
import { use, useEffect, useState } from "react";
import Link from "next/link";
import { Copy, Download, Send, ShieldX } from "lucide-react";
import { StatusBadge } from "@/components/status-badge";

type Detail={id:string;title:string;status:string;signer_name:string;signer_email:string;document_hash:string|null;final_hash:string|null;first_opened_at:string|null;last_opened_at:string|null;view_count:number;read_at:string|null;verified_at:string|null;signed_at:string|null;failure_reason:string|null;clients:{name:string;company:string|null};events:Array<{id:number;type:string;created_at:string}>};
export default function ContractDetail({params}:{params:Promise<{id:string}>}){const {id}=use(params);const [data,setData]=useState<Detail|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [link,setLink]=useState('');async function load(){const r=await fetch(`/api/contracts/${id}`);const b=await r.json();if(r.ok)setData(b);else setError(b.error)}useEffect(()=>{let active=true;fetch(`/api/contracts/${id}`).then(async r=>{const b=await r.json();if(!active)return;if(r.ok)setData(b);else setError(b.error)});return()=>{active=false}},[id]);async function action(name:'send'|'revoke'){setBusy(true);setError('');const r=await fetch(`/api/contracts/${id}/${name}`,{method:'POST'});const b=await r.json();setBusy(false);if(!r.ok){setError(b.error);return}if(b.url)setLink(b.url);await load()}
if(!data)return <p className="muted">{error||'Cargando…'}</p>;return <><div className="flex flex-wrap justify-between items-start gap-4 mb-7"><div><Link href="/admin/contratos" className="muted text-sm">← Contratos</Link><h1 className="text-3xl font-extrabold mt-2">{data.title}</h1><div className="mt-2"><StatusBadge status={data.status}/></div></div><div className="flex flex-wrap gap-2"><a className="btn btn-secondary" href={`/api/contracts/${id}/download?kind=pdf`}><Download size={17}/>PDF</a>{data.status==='SIGNED'&&<a className="btn btn-primary" href={`/api/contracts/${id}/download?kind=signed`}><Download size={17}/>Firmado</a>}{['READY','PENDING'].includes(data.status)&&<button className="btn btn-primary" disabled={busy} onClick={()=>action('send')}><Send size={17}/>{data.status==='PENDING'?'Regenerar enlace':'Enviar a firma'}</button>}{['READY','PENDING'].includes(data.status)&&<button className="btn btn-danger" disabled={busy} onClick={()=>action('revoke')}><ShieldX size={17}/>Revocar</button>}</div></div>
{error&&<p className="bg-red-50 text-red-700 rounded-lg p-3 mb-4">{error}</p>}{link&&<div className="card p-4 mb-5"><p className="font-bold mb-2">Enlace generado</p><div className="flex gap-2"><input className="input" readOnly value={link}/><button className="btn btn-secondary" onClick={()=>navigator.clipboard.writeText(link)}><Copy size={18}/></button></div></div>}
<div className="grid xl:grid-cols-[1fr_360px] gap-5"><section className="card p-6"><h2 className="font-extrabold text-lg mb-5">Información</h2><dl className="grid sm:grid-cols-2 gap-5 text-sm"><Info label="Cliente" value={data.clients?.name}/><Info label="Empresa" value={data.clients?.company||'—'}/><Info label="Firmante" value={data.signer_name}/><Info label="Correo" value={data.signer_email}/><Info label="Aperturas" value={String(data.view_count||0)}/><Info label="Leyó hasta el final" value={data.read_at?format(data.read_at):'No'}/><Info label="Correo verificado" value={data.verified_at?format(data.verified_at):'No'}/><Info label="Firmado" value={data.signed_at?format(data.signed_at):'No'}/></dl>{data.failure_reason&&<p className="mt-5 p-3 rounded bg-red-50 text-red-700 text-sm">{data.failure_reason}</p>}{data.document_hash&&<div className="mt-6"><p className="label">SHA-256 documento mostrado</p><code className="text-xs break-all muted">{data.document_hash}</code></div>}{data.final_hash&&<div className="mt-4"><p className="label">SHA-256 PDF firmado</p><code className="text-xs break-all muted">{data.final_hash}</code></div>}</section><aside className="card p-5"><h2 className="font-extrabold mb-4">Auditoría</h2><div className="space-y-4 max-h-[560px] overflow-auto">{data.events.map(e=><div key={e.id} className="border-l-2 border-teal-600 pl-3"><p className="font-bold text-sm">{eventLabel(e.type)}</p><p className="muted text-xs">{format(e.created_at)}</p></div>)}</div></aside></div></>}
function Info({label,value}:{label:string;value?:string|null}){return <div><dt className="muted">{label}</dt><dd className="font-bold mt-1">{value||'—'}</dd></div>}function format(v:string){return new Date(v).toLocaleString('es-CO',{timeZone:'America/Bogota'})}function eventLabel(v:string){const m:Record<string,string>={CREATED:'Contrato creado',CONVERTED:'Word convertido a PDF',SENT:'Enlace enviado',LINK_OPENED:'Enlace abierto',PDF_VIEWED:'PDF consultado',READ_TO_END:'Lectura completada',OTP_SENT:'Código enviado',OTP_FAILED:'Código incorrecto',OTP_BLOCKED:'Enlace bloqueado',EMAIL_VERIFIED:'Correo verificado',CONSENT_ACCEPTED:'Consentimiento aceptado',SIGNED:'Contrato firmado',DOWNLOADED:'Documento descargado',REVOKED:'Contrato revocado'};return m[v]||v}
